INSERT INTO Users (Username, Password)
VALUES ('admin', '1'),
('admin2', '1'),
('admin3', '1');


INSERT INTO Category (CategoryName)
VALUES ('Phone'),
('Laptop'),
('Tablet');

INSERT INTO Brand (BrandName)
VALUES ('Apple'),
('Samsung'),
('Oppo'),
('Asus');

INSERT INTO Color (ColorName, ColorValue)
VALUES ('Black','#000000'),
('White','#F8F8FF'),
('Blue','#0000FF'),
('Red','#FF0000');

INSERT INTO Size (Size)
VALUES (13),
(14),
(15.6),
(6.5),
(8),
(10);

INSERT INTO Ram (RamSize)
VALUES (2),
(4),
(8),
(10),
(12)

--/assets/images/Laptop/asus1.jpg

INSERT INTO 
Products (ProductName, ProductImg, RamID, BrandID, UnitPrice, ColorID, SizeID, UnitSellPrice, UnitInStock, [Description], CategoryID)
VALUES 
('Asus 1', '/assets/images/Laptop/asus1.jpg', 3, 4, 1000, 1, 3, 999.9, 20, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 2),
('Asus 2', '/assets/images/Laptop/asus2.jpg', 5, 4, 1000, 2, 3, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 2),
('Asus 3', '/assets/images/Laptop/asus3.jpg', 3, 4, 1000, 3, 3, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 2),
('Asus 4', '/assets/images/Laptop/asus4.jpg', 5, 4, 1000, 1, 3, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 2),
('Asus 5', '/assets/images/Laptop/asus5.jpg', 5, 4, 1000, 2, 3, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 2),

('iPad 1', '/assets/images/Apple/ipad1.jpg', 3, 1, 1000, 1, 5, 999.9, 20, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 3),
('iPad 2', '/assets/images/Apple/ipad2.jpg', 3, 1, 1000, 2, 6, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 3),
('iPad 3', '/assets/images/Apple/ipad3.jpg', 3, 1, 1000, 3, 5, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 3),
('iPad 4', '/assets/images/Apple/ipad4.jpg', 3, 1, 1000, 1, 6, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 3),
('iPad 5', '/assets/images/Apple/ipad5.jpg', 3, 1, 1000, 2, 5, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 3),

('Oppo 1', '/assets/images/Oppo/oppo1.jpg', 1, 3, 1000, 1, 1, 999.9, 20, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 1),
('Oppo 2', '/assets/images/Oppo/oppo1.jpg', 2, 3, 1000, 2, 2, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 1),
('Oppo 3', '/assets/images/Oppo/oppo1.jpg', 3, 3, 1000, 3, 3, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 1),
('Oppo 4', '/assets/images/Oppo/oppo1.jpg', 1, 3, 1000, 1, 1, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 1),
('Oppo 5', '/assets/images/Oppo/oppo1.jpg', 3, 3, 1000, 2, 2, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 1),

('Samsung 1', '/assets/images/Samsung/samsung1.jpg', 1, 2, 1000, 1, 1, 999.9, 20, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 1),
('Samsung 2', '/assets/images/Samsung/samsung2.jpg', 2, 2, 1000, 2, 2, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 1),
('Samsung 3', '/assets/images/Samsung/samsung3.jpg', 3, 2, 1000, 3, 3, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 1),
('Samsung 4', '/assets/images/Samsung/samsung4.jpg', 1, 2, 1000, 1, 1, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 1),
('Samsung 5', '/assets/images/Samsung/samsung5.jpg', 3, 2, 1000, 2, 2, 999.9, 50, 'The iPhone, created by Apple Inc., is a groundbreaking smartphone that revolutionized the way we communicate and interact with technology. With its sleek design, powerful performance, and user-friendly interface, the iPhone has become a symbol of innovation and sophistication. It offers a wide range of features, including a high-resolution display, advanced camera capabilities, secure biometric authentication, and access to a vast ecosystem of apps. The iPhone has played a significant role in shaping the modern mobile landscape and continues to set the standard for smartphones worldwide. Its seamless integration with other Apple devices and services further enhances its appeal, making it a popular choice among tech enthusiasts and everyday users alike.', 1)


INSERT INTO Reviews (UserID, ProductID, Rating, ReviewDate, LikeReact, [Content])
VALUES (1, 2, 4, GETDATE(), 10, 'Great laptop'),
       (1, 3, 5, GETDATE(), 15, 'Excellent performance'),
       (2, 3, 5, GETDATE(), 15, 'Excellent performance'),
       (3, 4, 3, GETDATE(), 5, 'Comfortable shirt'),
       (1, 5, 4, GETDATE(), 10, 'Great laptop'),
       (2, 6, 5, GETDATE(), 15, 'Excellent performance'),
       (3, 7, 4, GETDATE(), 10, 'Great laptop'),
       (1, 8, 5, GETDATE(), 15, 'Excellent performance'),
       (2, 9, 4, GETDATE(), 10, 'Great laptop'),
       (3, 10, 5, GETDATE(), 15, 'Excellent performance'),
       (1, 11, 4, GETDATE(), 10, 'Great laptop'),
       (2, 12, 5, GETDATE(), 15, 'Excellent performance'),
       (3, 13, 5, GETDATE(), 15, 'Excellent performance')
INSERT INTO Comments (UserID, ReviewID, CommentDate, LikeReact, Comment)
VALUES (2, 1, '2023-05-30', 3, 'A great phone!'),
(3, 1, '2023-05-30', 2, 'I prefer Android though.'),
(1, 3, '2023-05-31', 5, 'Glad you like it!'),
(2, 3, '2023-05-31', 1, 'Is the camera good?'),
(3, 4, '2023-05-30', 0, 'Not my style.')